import {Component} from '@angular/core';
import {MatInputModule} from '@angular/material/input';
import {MatFormFieldModule} from '@angular/material/form-field';
import { FormGroup, FormControl, Validators, FormsModule } from '@angular/forms';
import { ScostosService } from '../../../Services/servcostos/scostos.service'; // Asegúrate de tener la ruta correcta
import { CostoFijo,CostoVariable } from 'src/app/Interfaz/costos';
import { MatSnackBar } from '@angular/material/snack-bar';
import * as bootstrap from 'bootstrap';


@Component({
  selector: 'app-costosoperacionales',
  templateUrl: './costosoperacionales.component.html',
  styleUrls: ['./costosoperacionales.component.css']
})
export class CostosoperacionalesComponent {

  

  costoFijoForm = new FormGroup({
    concepto: new FormControl('', Validators.required),
    monto: new FormControl('', Validators.required),
    fechacostofijo: new FormControl('', Validators.required),

  });
    costoVariableForm = new FormGroup({
      concepto: new FormControl('', Validators.required),
      monto: new FormControl('', Validators.required),
      fechacostovariable: new FormControl('', Validators.required),

})



constructor(private scostosService: ScostosService,
  private snackBar: MatSnackBar
  
  ) { }

onSubmit() {
  if (this.costoFijoForm.valid) {
    const formValue = this.costoFijoForm.value;

    // Convertir valores del formulario asegurándose de que no son null o undefined
    const monto = formValue.monto != null ? parseFloat(formValue.monto) : 0;
    const fechacostofijo = formValue.fechacostofijo != null ? new Date(formValue.fechacostofijo) : new Date();

    // Asumiendo que la interfaz se llama CostoFijo (con C mayúscula)
    const costoFijo: CostoFijo = {
      // Omit the id if it is auto-generated by the backend
      concepto: formValue.concepto || '', // Fallback to empty string if null or undefined
      monto: isNaN(monto) ? 0 : monto, // Fallback to 0 if monto is NaN
      fechacostofijo: formValue.fechacostofijo|| '',
    };

    this.scostosService.addcostofijo(costoFijo).subscribe({
      next: (costoFijo) => {
        console.log('Costo fijo registrado:', costoFijo);

        this.snackBar.open('Registro exitoso.', 'Cerrar', {
          duration: 2000,});
        // Reset the form or handle success
         // Reset the form to clear fields
         this.costoFijoForm.reset();
      },
      error: (error) => {
        console.error('Ocurrió un error:', error);
        this.snackBar.open('Ocurrió un error al registrar el costo fijo.', 'Cerrar', {
          duration: 2000,
        });
      },
    });
  }else {
    // If the form is not valid, you can alert the user to check their input
    alert('Por favor complete el formulario correctamente antes de enviar.');
}
}


onSubmitvariable() {
  if (this.costoVariableForm.valid) {
    const formValue = this.costoVariableForm.value;

    // Convertir valores del formulario asegurándose de que no son null o undefined
    const monto = formValue.monto != null ? parseFloat(formValue.monto) : 0;
    const fechacostovariable = formValue.fechacostovariable != null ? new Date(formValue.fechacostovariable) : new Date();

    // Asumiendo que la interfaz se llama CostoFijo (con C mayúscula)
    const CostoVariable: CostoVariable = {
      // Omit the id if it is auto-generated by the backend
      concepto: formValue.concepto || '', // Fallback to empty string if null or undefined
      monto: isNaN(monto) ? 0 : monto, // Fallback to 0 if monto is NaN
      fechacostovariable: formValue.fechacostovariable|| '',
    };

    this.scostosService.addcostovariable(CostoVariable).subscribe({
      next: (CostoVariable) => {
        console.log('Costo fijo registrado:', CostoVariable);

        this.snackBar.open('Registro exitoso.', 'Cerrar', {
          duration: 2000,});
        // Reset the form or handle success
         // Reset the form to clear fields
         this.costoVariableForm.reset();
      },
      error: (error) => {
        console.error('Ocurrió un error:', error);
        this.snackBar.open('Ocurrió un error al registrar el costo fijo.', 'Cerrar', {
          duration: 2000,
        });
      },
    });
  }else {
    // If the form is not valid, you can alert the user to check their input
    alert('Por favor complete el formulario correctamente antes de enviar.');
}
}


openModal() {
  const element = document.getElementById('miModal');
 
  if (element) {
    const myModal = new bootstrap.Modal(element, {
      keyboard: false
    });
    myModal.show();
  } else {
    console.error('Modal element not found');
  }
}


openModalvariable() {
  const element = document.getElementById('miModalvariable');
 
  if (element) {
    const myModal = new bootstrap.Modal(element, {
      keyboard: false
    });
    myModal.show();
  } else {
    console.error('Modal element not found');
  }

}

navegarAdifoperacion(): void {

  window.open('/difoperacion', '_blank', 'toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=600,height=600');

}}

